EduCord/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('institute/', views.institute, name = 'institute'),

    path('login/', views.login, name = 'login'),
    path('logout/', views.Logout.as_view(), name = 'logout'),

    path('student/personalinfo/', views.personalinfo, name = 'personalinfo'),
    path('student/timetable/', views.timetable, name = 'timetable'),
    path('student/attendance/', views.attendance, name = 'attendance'),
    path('student/feepayment/', views.feepayment, name = 'feepayment'),
    path('student/applicationform/', views.applicationform, name = 'applicationform'),
]

main/models.py
from django.db import models

# Create your models here.
class Address(models.Model):
    line1 = models.CharField(max_length=256)
    line2 = models.CharField(max_length=256)
    city = models.CharField(max_length=256)
    state = models.CharField(max_length=256)
    country = models.CharField(max_length=256)
    pincode = models.CharField(max_length=256)

    class Meta:
        verbose_name_plural = "Address"

class Institute(models.Model):
    name = models.CharField(max_length=256)
    branch = models.CharField(max_length=256)
    address = models.OneToOneField(Address, on_delete=models.CASCADE)
    phone = models.CharField(max_length=256)

    def get_branch_list(self):
        return self.branch.split(',')

    def __str__(self):
        return self.name

class Student(models.Model):
    GENDER = (
        ('m', 'Male'),
        ('f', 'Female')
    )
    roll_no = models.CharField(max_length = 256)
    dob = models.DateField()
    gender = models.CharField(max_length = 1, choices = GENDER)
    branch = models.CharField(max_length=256)
    institute = models.ForeignKey(Institute, on_delete=models.CASCADE)
    phone = models.CharField(max_length=15)

    father_name = models.CharField(max_length=256)
    father_phone = models.CharField(max_length=256)
    father_email = models.EmailField()

    mother_name = models.CharField(max_length=256)
    mother_phone = models.CharField(max_length=256)
    mother_email = models.EmailField()

    annual_income = models.CharField(max_length=20)
    has_institute_access = models.BooleanField(default=False)

    image = models.CharField(max_length=256, default = '/static/img/default-user-image.png')
    def __str__(self):
        return self.roll_no

class Student_Address(models.Model):
    address = models.OneToOneField(Address, on_delete=models.CASCADE)
    student = models.OneToOneField(Student, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Student Address"

class TimeTable(models.Model):
    DAY_NAMES = (
        ('0', 'Monday'),
        ('1', 'Tuesday'),
        ('2', 'Wednesday'),
        ('3', 'Thursday'),
        ('4', 'Friday'),
        ('5', 'Saturday'),
        ('6', 'Sunday'),
    )
    # 05:00
    start_time = models.CharField(max_length=5)
    day = models.CharField(max_length = 1, choices = DAY_NAMES)
    # In Minutes
    duration = models.CharField(max_length=5, default = '60')
    course = models.CharField(max_length=20)
    branch = models.CharField(max_length=20)

    class Meta:
        verbose_name_plural = "Time Table"

class Attendance(models.Model):
    time_table = models.ForeignKey(TimeTable, on_delete=models.CASCADE)
    date = models.DateField()

    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    is_present = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Attendance"


class FeePayment(models.Model):
    branch = models.CharField(max_length=256)
    description = models.CharField(max_length=256)
    amount = models.CharField(max_length=10)
    start_date = models.DateField()
    end_date = models.DateField()

    class Meta:
        verbose_name_plural = "Fee Payment"

class FeePaymentStatus(models.Model):
    PAYMENT_STATUS = (
        ('p', 'Paid'),
        ('u', 'Unpaid'),
    )
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    fees = models.ForeignKey(FeePayment, on_delete=models.CASCADE)
    status = models.CharField(max_length=1, choices=PAYMENT_STATUS)

    class Meta:
        verbose_name_plural = "Fee Payment Status"

class Application(models.Model):
    applicant = models.ForeignKey(Student, on_delete=models.CASCADE)
    department = models.CharField(max_length=256)
    subject = models.CharField(max_length=256)
    status = models.CharField(max_length=256)
    applied_on = models.DateTimeField(auto_now_add=True)
    content = models.CharField(max_length=256)

class Subscribe(models.Model):
    email = models.EmailField()

main/forms.py
from django import forms
from main import models

class LoginForm(forms.Form):
    username = forms.CharField(max_length=10)
    password = forms.CharField(widget = forms.PasswordInput)

class AddressForm(forms.ModelForm):
    class Meta:
        model = models.Address
        fields = '__all__'

class ApplicationForm(forms.ModelForm):
    class Meta:
        model = models.Application
        fields = '__all__'

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login as auth_login
from django.core.exceptions import ObjectDoesNotExist

from django.contrib.auth.views import LogoutView

from main import forms, models

# Create your views here.
def index(request):
    context = {
        "index": True,
    }
    return render(request, 'main/index.html', context)

def institute(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/login/?next=/institute/')

    context = {
        "institute": True,
    }
    if request.method == 'POST':
        if request.POST.get('institute_id', None):
            # View
            institute_instance = models.Institute.objects.get(id = request.POST['institute_id'])
            context['institute_instance'] = institute_instance
        elif request.POST.get('institute_instance_id', None):
            # Update
            pass
        else:
            # Create
            branch_string = ''
            for i in dict(request.POST)['branch']:
                branch_string += i + ','
            branch_string = branch_string[:-1]
            addressForm = forms.AddressForm(request.POST)
            address = addressForm.save()
            institute_instance = {
                "name": request.POST['name'],
                "branch": branch_string,
                "address": address,
                "phone": request.POST['phone'],
            }
            models.Institute.objects.create(**institute_instance)

    context["institutes"] = models.Institute.objects.all()
    return render(request, 'main/institute.html', context)

# ===================== Student =====================
def login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/')

    error = None
    if request.method == 'POST':
        loginForm = forms.LoginForm(request.POST)
        if loginForm.is_valid():
            username = loginForm.cleaned_data['username']
            password = loginForm.cleaned_data['password']
            user = authenticate(username = username, password = password)
            if user:
                # creates session for user in request variable
                auth_login(request, user)
                if 'next' in request.GET:
                    return HttpResponseRedirect(request.GET['next'])
                return HttpResponseRedirect('/')
            else:
                error = 'Invalid username or password'
    context = {
        "error": error,
        "login": True,
    }
    return render(request, 'main/login.html', context)

class Logout(LogoutView):
    next_page = '/'

def personalinfo(request):
    context = {
        "student": True,
        "personalinfo": True,
        "student_instance": models.Student.objects.get(roll_no=request.user.get_username())
    }
    return render(request, 'main/student/personalinfo.html', context)

def timetable(request):
    student = models.Student.objects.get(roll_no=request.user.get_username())
    context = {
        "student": True,
        "timetable": True,
        "time_table_instance": {},
    }
    days = ['Mon', 'Tue', 'Wed', 'Thur', 'Fri', 'Sat', 'Sun']
    for i in range(len(days)):
        day_table = {}
        for j in range(18 - 8):
            start_time = j + 8
            if start_time < 10:
                start_time = '0' + str(start_time)
            try:
                curr = models.TimeTable.objects.get(day = str(i), start_time = str(start_time) + ":00", branch = student.branch).course
            except ObjectDoesNotExist:
                curr = "-"
            day_table[str(start_time)] = curr
        context['time_table_instance'][days[i]] = day_table
    return render(request, 'main/student/timetable.html', context)

def attendance(request):
    context = {
        "student": True,
        "attendance": True,
        "attendance_instance": {},
    }
    if request.method == 'POST':
        student = models.Student.objects.get(roll_no=request.user.get_username())
        from datetime import datetime, timedelta
        date = datetime.strptime(request.POST['start_date'], "%Y-%m-%d").date()
        end_date = datetime.strptime(request.POST['end_date'], "%Y-%m-%d").date()
        dates = []
        i = 0
        while date <= end_date:
            date_table = {}
            for j in range(18 - 8):
                start_time = j + 8
                if start_time < 10:
                    start_time = '0' + str(start_time)
                try:
                    time_table = models.TimeTable.objects.get(day = date.weekday(), start_time = str(start_time) + ":00", branch = student.branch)
                    curr = models.Attendance.objects.get(date = date, time_table_id = time_table.id, student_id = student.id)
                    curr = 'P' if curr.is_present else 'A'
                except ObjectDoesNotExist:
                    curr = "-"
                date_table[str(start_time)] = curr

            context['attendance_instance'][date] = date_table
            dates.append(date)
            i += 1
            date += timedelta(days=1)

    return render(request, 'main/student/attendance.html', context)

def feepayment(request):
    if request.method == 'POST':
        # Update
        models.FeePaymentStatus.objects.filter(id=request.POST['feepaymentstatus_id']).update(status='p')

    # List
    student = models.Student.objects.get(roll_no=request.user.get_username())
    try:
        feepayments = models.FeePaymentStatus.objects.filter(student_id=student.id)
    except ObjectDoesNotExist:
        feepayments = []

    context = {
        "student": True,
        "feepayment": True,
        "feepayments": feepayments,
    }
    return render(request, 'main/student/feepayment.html', context)

def applicationform(request):
    student = models.Student.objects.get(roll_no=request.user.get_username())

    context = {
        "student": True,
        "applicant": student.id,
        "applicationform": True,
    }
    if request.method == 'POST':
        if request.POST.get('application_id', None):
            # View
            application_instance = models.Application.objects.get(id = request.POST['application_id'])
            context['application_instance'] = application_instance
        else:
            # Create
            application = forms.ApplicationForm(request.POST)
            if application.is_valid():
                application.save()

    context["applicationforms"] = models.Application.objects.filter(applicant_id=student.id)
    return render(request, 'main/student/applicationform.html', context)

templates/main/student/applicationform.html
{% extends 'main/student/base.html' %}
{% load static %}

{% block studentcontent %}
        <h2>Applications</h2>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>S.No.</th>
                        <th>Application Id</th>
                        <th>Subject</th>
                        <th>Status</th>
                        <th>Date</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in applicationforms %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ i.id }}</td>
                        <td>{{ i.subject }}</td>
                        <td>{{ i.status }}</td>
                        <td>{{ i.applied_on }}</td>
                        <td>
                            <form action="" method="post">
                                {% csrf_token %}
                                <input type="text" name="application_id" value="{{ i.id }}" hidden>
                                <button type="submit" class="btn btn-primary btn-sm">
                                    View
                                </button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <form action="" method="post">
            {% csrf_token %}
            <input type="text" name="applicant" value="{{applicant}}" hidden>
            <input type="text" name="status" value="Under Verification" hidden>
            <div class="form-group">
                <label for="department">Department</label>
                <input type="text" class="form-control" name="department" placeholder="Enter Department" value="{{application_instance.department}}" {% if application_instance %}disabled{% endif %}>
            </div>
            <div class="form-group">
                <label for="subject">Subject</label>
                <input type="text" class="form-control" name="subject" placeholder="Enter Subject" value="{{application_instance.subject}}" {% if application_instance %}disabled{% endif %}>
            </div>
            <div class="form-group">
                <label for="content">Content</label>
                <textarea type="text" class="form-control" name="content" placeholder="Enter Content" rows="5" {% if application_instance %}disabled{% endif %}>{{application_instance.content}}</textarea>
            </div>
            {% if not application_instance %}
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
            {% endif %}
        </form>
{% endblock %}

templates/main/student/attendance.html
{% extends 'main/student/base.html' %}
{% load static %}

{% block studentcontent %}
        <h2>Attendance</h2>
        <form class="form-inline" action="" method="post">
            {% csrf_token %}
            <div class="form-group mb-2">
                <input type="text" name="start_date" class="form-control-plaintext" placeholder="Start Date" onfocus="(this.type='date')" onblur="(this.type='text')">
            </div>
            <div class="form-group mb-2">
                <input type="text" name="end_date" class="form-control-plaintext" placeholder="End Date" onfocus="(this.type='date')" onblur="(this.type='text')">
            </div>
            <button type="submit" class="btn btn-primary mb-2">Get Attendance</button>
        </form>

        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>08:00 Hrs</th>
                        <th>09:00 Hrs</th>
                        <th>10:00 Hrs</th>
                        <th>11:00 Hrs</th>
                        <th>12:00 Hrs</th>
                        <th>13:00 Hrs</th>
                        <th>14:00 Hrs</th>
                        <th>15:00 Hrs</th>
                        <th>16:00 Hrs</th>
                        <th>17:00 Hrs</th>
                    </tr>
                </thead>
                <tbody>
                    {% for date, date_attendance in attendance_instance.items %}
                    <tr>
                        <th>{{ date }}</th>
                        <td>{{ date_attendance.08 }}</td>
                        <td>{{ date_attendance.09 }}</td>
                        <td>{{ date_attendance.10 }}</td>
                        <td>{{ date_attendance.11 }}</td>
                        <td>{{ date_attendance.12 }}</td>
                        <td>{{ date_attendance.13 }}</td>
                        <td>{{ date_attendance.14 }}</td>
                        <td>{{ date_attendance.15 }}</td>
                        <td>{{ date_attendance.16 }}</td>
                        <td>{{ date_attendance.17 }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
{% endblock %}

templates/main/student/base.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
    Student
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/student.css' %}">
    <style>
        .table td, th {
            text-align: center;   
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link {% if personalinfo %}active{% endif %}" href="{% url 'personalinfo' %}">
                                <i class="fas fa-user-edit"></i>
                                Personal Info <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if timetable %}active{% endif %}" href="{% url 'timetable' %}">
                                <i class="fas fa-calendar-alt"></i>
                                Time Table
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if attendance %}active{% endif %}" href="{% url 'attendance' %}">
                                <i class="fas fa-user-check"></i>
                                Attedance
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if feepayment %}active{% endif %}" href="{% url 'feepayment' %}">
                                <i class="fas fa-receipt"></i>
                                Fee Payments
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if applicationform %}active{% endif %}" href="{% url 'applicationform' %}">
                                <i class="fas fa-file"></i>
                                Applications
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2">Student Name</h1>
            <div class="btn-toolbar mb-2 mb-md-0" id="lolol">
                <div class="btn-group mr-2">
                    <a href="{% url 'personalinfo' %}" class="btn btn-sm btn{% if not personalinfo %}-outline{% endif %}-secondary">
                        <i class="fas fa-user-edit"></i>
                        Personal Info
                    </a>
                    <a href="{% url 'timetable' %}" class="btn btn-sm btn{% if not timetable %}-outline{% endif %}-secondary">
                        <i class="fas fa-calendar-alt"></i>
                        Time Table
                    </a>
                    <a href="{% url 'attendance' %}" class="btn btn{% if not attendance %}-outline{% endif %}-secondary">
                        <i class="fas fa-user-check"></i>
                        Attedance
                    </a>
                    <a href="{% url 'feepayment' %}" class="btn btn{% if not feepayment %}-outline{% endif %}-secondary">
                        <i class="fas fa-receipt"></i>
                        Fee Payments
                    </a>
                    <a href="{% url 'applicationform' %}" class="btn btn{% if not applicationform %}-outline{% endif %}-secondary">
                        <i class="fas fa-file"></i>
                        Applications
                    </a>
                </div>
            </div>
        </div>

        {% block studentcontent %}{% endblock %}

    </main>
{% endblock %}

templates/main/student/feepayment.html
{% extends 'main/student/base.html' %}
{% load static %}

{% block studentcontent %}
        <h2>Fee Payment</h2>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>S.No.</th>
                        <th>Description</th>
                        <th>Amount(in INR)</th>
                        <th>Duration</th>
                        <th>Status</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in feepayments %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ i.fees.description }}</td>
                        <td><i class="fas fa-rupee-sign"></i> {{ i.fees.amount }}</td>
                        <td>{{ i.fees.start_date }} - {{ i.fees.end_date }}</td>
                        <td>{{ i.get_status_display }}</td>
                        <td>
                            <form action="" method="post">
                                {% csrf_token %}
                                <input type="text" name="feepaymentstatus_id" value="{{i.id}}" hidden>
                                <button type="submit" class="btn btn-primary btn-sm" {% if i.status == 'p' %}disabled{% endif %}>
                                    Pay
                                </button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
{% endblock %}

templates/main/student/personalinfo.html
{% extends 'main/student/base.html' %}
{% load static %}

{% block studentcontent %}
        <h2>Personal Info</h2>
        <div class="table-responsive">
            <img src="{{ student_instance.image }}" class="float-right rounded img-thumbnail img-fluid" style="max-height: 10rem">
            <table class="table col-4 table-borderless">
                <tbody>
                    <tr>
                        <th>Roll Number</th>
                        <th>{{ student_instance.roll_no }}</th>
                    </tr>
                    <tr>
                        <th>Name</th>
                        <th>{{ user.first_name }} {{ user.last_name }}</th>
                    </tr>
                    <tr>
                        <th>DOB</th>
                        <th>{{ student_instance.dob }}</th>
                    </tr>
                    <tr>
                        <th>Gender</th>
                        <th>{{ student_instance.get_gender_display }}</th>
                    </tr>
                    <tr>
                        <th>Branch</th>
                        <th>{{ student_instance.branch }}</th>
                    </tr>
                    <tr>
                        <th>College</th>
                        <th>{{ student_instance.institute.name }}</th>
                    </tr>
                    <tr>
                        <th>Phone</th>
                        <th>{{ student_instance.phone }}</th>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <th>{{ user.email }}</th>
                    </tr>
                    <tr>
                        <th><h5>Parent Details</h5></th>
                        <th></th>
                    </tr>
                    <tr>
                        <th>Father Name</th>
                        <th>{{ student_instance.father_name }}</th>
                    </tr>
                    <tr>
                        <th>Father Phone</th>
                        <th>{{ student_instance.father_phone }}</th>
                    </tr>
                    <tr>
                        <th>Father Email</th>
                        <th>{{ student_instance.father_email }}</th>
                    </tr>
                    <tr>
                        <th>Mother Name</th>
                        <th>{{ student_instance.mother_name }}</th>
                    </tr>
                    <tr>
                        <th>Mother Phone</th>
                        <th>{{ student_instance.mother_phone }}</th>
                    </tr>
                    <tr>
                        <th>Mother Email</th>
                        <th>{{ student_instance.mother_email }}</th>
                    </tr>
                    <tr>
                        <th>Parents Annual Income</th>
                        <th><i class="fas fa-rupee-sign"></i> {{ student_instance.annual_income }}</th>
                    </tr>
                </tbody>
            </table>
        </div>
{% endblock %}

templates/main/student/timetable.html
{% extends 'main/student/base.html' %}
{% load static %}

{% block studentcontent %}
        <h2>Time Table</h2>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Day</th>
                        <th>08:00 Hrs</th>
                        <th>09:00 Hrs</th>
                        <th>10:00 Hrs</th>
                        <th>11:00 Hrs</th>
                        <th>12:00 Hrs</th>
                        <th>13:00 Hrs</th>
                        <th>14:00 Hrs</th>
                        <th>15:00 Hrs</th>
                        <th>16:00 Hrs</th>
                        <th>17:00 Hrs</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>Mon</th>
                        <td>{{ time_table_instance.Mon.08 }}</td>
                        <td>{{ time_table_instance.Mon.09 }}</td>
                        <td>{{ time_table_instance.Mon.10 }}</td>
                        <td>{{ time_table_instance.Mon.11 }}</td>
                        <td>{{ time_table_instance.Mon.12 }}</td>
                        <td>{{ time_table_instance.Mon.13 }}</td>
                        <td>{{ time_table_instance.Mon.14 }}</td>
                        <td>{{ time_table_instance.Mon.15 }}</td>
                        <td>{{ time_table_instance.Mon.16 }}</td>
                        <td>{{ time_table_instance.Mon.17 }}</td>
                    </tr>
                    <tr>
                        <th>Tue</th>
                        <td>{{ time_table_instance.Tue.08 }}</td>
                        <td>{{ time_table_instance.Tue.09 }}</td>
                        <td>{{ time_table_instance.Tue.10 }}</td>
                        <td>{{ time_table_instance.Tue.11 }}</td>
                        <td>{{ time_table_instance.Tue.12 }}</td>
                        <td>{{ time_table_instance.Tue.13 }}</td>
                        <td>{{ time_table_instance.Tue.14 }}</td>
                        <td>{{ time_table_instance.Tue.15 }}</td>
                        <td>{{ time_table_instance.Tue.16 }}</td>
                        <td>{{ time_table_instance.Tue.17 }}</td>
                    </tr>
                    <tr>
                        <th>Wed</th>
                        <td>{{ time_table_instance.Wed.08 }}</td>
                        <td>{{ time_table_instance.Wed.09 }}</td>
                        <td>{{ time_table_instance.Wed.10 }}</td>
                        <td>{{ time_table_instance.Wed.11 }}</td>
                        <td>{{ time_table_instance.Wed.12 }}</td>
                        <td>{{ time_table_instance.Wed.13 }}</td>
                        <td>{{ time_table_instance.Wed.14 }}</td>
                        <td>{{ time_table_instance.Wed.15 }}</td>
                        <td>{{ time_table_instance.Wed.16 }}</td>
                        <td>{{ time_table_instance.Wed.17 }}</td>
                    </tr>
                    <tr>
                        <th>Thur</th>
                        <td>{{ time_table_instance.Thur.08 }}</td>
                        <td>{{ time_table_instance.Thur.09 }}</td>
                        <td>{{ time_table_instance.Thur.10 }}</td>
                        <td>{{ time_table_instance.Thur.11 }}</td>
                        <td>{{ time_table_instance.Thur.12 }}</td>
                        <td>{{ time_table_instance.Thur.13 }}</td>
                        <td>{{ time_table_instance.Thur.14 }}</td>
                        <td>{{ time_table_instance.Thur.15 }}</td>
                        <td>{{ time_table_instance.Thur.16 }}</td>
                        <td>{{ time_table_instance.Thur.17 }}</td>
                    </tr>
                    <tr>
                        <th>Fri</th>
                        <td>{{ time_table_instance.Fri.08 }}</td>
                        <td>{{ time_table_instance.Fri.09 }}</td>
                        <td>{{ time_table_instance.Fri.10 }}</td>
                        <td>{{ time_table_instance.Fri.11 }}</td>
                        <td>{{ time_table_instance.Fri.12 }}</td>
                        <td>{{ time_table_instance.Fri.13 }}</td>
                        <td>{{ time_table_instance.Fri.14 }}</td>
                        <td>{{ time_table_instance.Fri.15 }}</td>
                        <td>{{ time_table_instance.Fri.16 }}</td>
                        <td>{{ time_table_instance.Fri.17 }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
{% endblock %}